name: Validate_Azure_Credentials

on:
  #lo comentado es para ejecutar on demand
  #schedule:
    # * is a special character in YAML so you have to quote this string
   # - cron:  '0 13 * * 1,2,3,4,5'
  workflow_dispatch

jobs:

  Validate-Azure-Credentials:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
  Azure-Credential-is-Working:
    if: ${{ success() }}
    needs:  Validate-Azure-Credentials
    runs-on: ubuntu-latest
    steps:
      - name: Azure Credential is Working
        run: echo Azure Credential is Working!
